# application.properties
# 환경변수 key 생성 공식 : key 값을 점(.)과 하이픈(-)을 언더바(_)로 바꾸고 대문자로 만든다. (권장)
# 환경변수 key 생성 공식 -> 없다면 ${} 안에 key 값으로 env 값 조회

# -----------------------------------------
# settings
# -----------------------------------------

# DB 설정
db.driver=org.postgresql.Driver
db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}

# ldap
ldap.url=https://int-in.tbapi.kt.com/ldap/v3.0/
ldap.aes-key=${LDAP_AES_KEY}
ldap.conn-id=${LDAP_CONN_ID}
ldap.conn-pwd=${LDAP_CONN_PWD}
ldap.api-id=${LDAP_API_ID}
ldap.api-pwd=${LDAP_API_PWD}

# security
security.cookie.secure=${SECURITY_COOKIE_SECURE:true}

# -----------------------------------------
# path
# -----------------------------------------

# url
url.domain=${URL_DOMAIN}
url.portal=${URL_PORTAL}
url.admin=${URL_ADMIN}

url.stream=stream
url.cdn = https://ktedufrontdoor-hrgpcfgwgkdsdghw.a02.azurefd.net
url.video = /vod/miniLecture/video/

# -----------------------------------------
# key
# -----------------------------------------

# app
app.enc-key=${APP_ENC_KEY}
lms.secret-key=${LMS_ENC_KEY}

# jwt
jwt.secret-key=${JWT_SECRET_KEY}
jwt.access-key=${JWT_ACCESS_KEY}
jwt.refresh-key=${JWT_REFRESH_KEY}

# naver map key
naver.map.key=${NAVER_MAP_KEY}

# -----------------------------------------
# sso
# -----------------------------------------

# azure sso
azure.sso.success-redirect-url-oidc=/api/entra-sso/callback
azure.sso.keyvault.secret.vault-name=${AZURE_KEYVAULT_NAME}

