# application-portal.properties
# 나중에 프로젝트 분리 시 application.properties 에 병합

# src/conf/cresys.properties
# saml.properties - 유지

# src/conf/cresys_service.properties - 삭제
# src/conf/bulletin.properties - 삭제
# src/conf/credu_ko.properties - 삭제
# src/conf/mail.properties - 삭제
# menu_name.properties, menu_depth.properties - 삭제
# scorm2004.properties - 삭제

# kt exam
exam.domain=${URL_EXAM}
exam.secret-key=${EXAM_SECRET_KEY}

# codegenius
codegenius.domain = https://dev.codegenius.edu-tech.io/
codegenius.enckey =

# fastcampus
fastcampus.domain = https://skillflo.io/external/sso
fastcampus.enckey =

# ai
openai.model=gpt-4.1-mini
api.openai-key=${API_OPENAI_KEY}
gemini.model=gemini-2.5-flash
api.gemini-key=${API_GEMINI_KEY}
