# application-portal.properties
# 나중에 프로젝트 분리 시 application.properties 에 병합

# src/conf/cresys.properties
# saml.properties - 유지

# src/conf/cresys_service.properties - 삭제
# src/conf/bulletin.properties - 삭제
# src/conf/credu_ko.properties - 삭제
# src/conf/mail.properties - 삭제
# menu_name.properties, menu_depth.properties - 삭제
# scorm2004.properties - 삭제

# kt exam
exam.domain=${URL_EXAM}
exam.secret-key=${EXAM_SECRET_KEY}

# codegenius
codegenius.domain = https://dev.codegenius.edu-tech.io/
codegenius.enckey =

# fastcampus
fastcampus.domain = https://skillflo.io/external/sso
fastcampus.enckey =

# ai
openai.model=gpt-4.1-mini
api.openai-key=${API_OPENAI_KEY}
gemini.model=gemini-2.5-flash
api.gemini-key=${API_GEMINI_KEY}


### TODO 남겨둘 후보 property - 작업 해야함
# source: src/conf/spring/KT-properties.xml#inline
IMAGE_PATH=/anymobi/img/

# source: src/conf/cresys.properties
SCORM2004.LOG.DIR=C:/workspace/202506_ptl/WebContent/log
SCORM2004.LOG.PROPERTIES=C:/workspace/202506_ptl/WebContent/WEB-INF/classes/conf/scorm2004.properties
SCORM2004.REALPATH.SERVER1=C:/workspace/202506_ptl/WebContent/content/scorm2004
SCORM2004.WEBPATH.SERVER1=/content/scorm2004
bulletin.file.name=C:/workspace/202506_ptl/WebContent/WEB-INF/classes/conf/bulletin.properties
com.sericeo.corpcode=6034
com.sericeo.enckey=

# source: src/conf/spring/KT-properties.xml#inline
database_log_manage=false
database_log_manage_query_id=adm.logs.insertLogs

# source: src/conf/cresys.properties
db.ktedudb=
db.kzoavjtm=
db.secret=
dir.db.LICENSE=/dp/bulletin/licenseAtt
dir.db.OUTLECT=/dp/bulletin/outLect
dir.home=C:/workspace/202506_ptl/WebContent/
dir.path.QNA=/dp/bulletin/boards/qna
dir.path.cash=/dp/cash
dir.path.exam.file=/dp/exam/file
dir.path.examcourse.file=/dp/examcourse/file
dir.path.ibox=/dp/bulletin/ibox
dir.path.learncom.Cop.pathActFinalReport=/dp/bulletin/learncom/cop/actFinalReport
dir.path.learncom.Cop.pathActMiddleReport=/dp/bulletin/learncom/cop/actMiddleReport
dir.path.learncom.Cop.pathBoard=/dp/bulletin/learncom/cop/board
dir.path.textbook=/dp/textbook/
dir.upload=project;exam;research;researchmng;researcdomng;tutor;sulmun;etest;damun;accept;scobject;edutarget;class;linksite;outuseradmin;etestquestion;proposewizard;blofflineinterview;blcompleteaction;studyadmindata;qnabycourse;studyadminboard;report;goyong;knowledgeucc;resource;subject;blogfile;postfile;community;liktboard;mentoinfo;caconfig;banner;sepcialeduhistory;
dir.upload.BOARD=C:/workspace/202506_ptl/WebContent/dp/bulletin/board/subj
dir.upload.CJ=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/self_exam
dir.upload.CenterDeskEvent=C:/workspace/202506_ptl/WebContent/dp/bulletinaa/
dir.upload.DIC=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/word
dir.upload.FA=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/ifaq
dir.upload.LEADER=C:/workspace/202506_ptl/WebContent/dp/bulletin/online/leader
dir.upload.LICENSE=C:/workspace/202506_ptl/WebContent/dp/bulletin/licenseAtt
dir.upload.MANAGE=C:/workspace/202506_ptl/WebContent/dp/bulletin/online/manage
dir.upload.OUTLECT=C:/workspace/202506_ptl/WebContent/dp/bulletin/outLect
dir.upload.QNA=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/qna
dir.upload.SB=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/notice
dir.upload.SD=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/pds
dir.upload.SQ=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/free
dir.upload.SYSTEM=C:/workspace/202506_ptl/WebContent/dp/bulletin/online/system
dir.upload.accept=C:/workspace/202506_ptl/WebContent/dp/accept/
dir.upload.banner=C:/workspace/202506_ptl/WebContent/dp/banner/
dir.upload.blcompleteaction=C:/workspace/202506_ptl/WebContent/dp/blcompleteaction/
dir.upload.blofflineinterview=C:/workspace/202506_ptl/WebContent/dp/blofflineinterview/
dir.upload.blogfile=C:/workspace/202506_ptl/WebContent/eportfolio/uploads/blog/
dir.upload.blpositionmanager=C:/workspace/202506_ptl/WebContent/dp/blpositionmanager/
dir.upload.books=C:/workspace/202506_ptl/WebContent/dp/books/
dir.upload.bulletin=C:/workspace/202506_ptl/WebContent/dp/bulletin/
dir.upload.caconfig=C:/workspace/202506_ptl/WebContent/dp/subject/accept/
dir.upload.careerachieve=C:/workspace/202506_ptl/WebContent/eportfolio/uploads/career/
dir.upload.careerbasicinfo=C:/workspace/202506_ptl/WebContent/eportfolio/uploads/career/
dir.upload.cash=C:/workspace/202506_ptl/WebContent/dp/cash
dir.upload.class=C:/workspace/202506_ptl/WebContent/dp/accept/
dir.upload.community=C:/workspace/202506_ptl/WebContent/dp/community/
dir.upload.contentsboard=C:/workspace/202506_ptl/WebContent/dp/contentsboard/
dir.upload.damun=C:/workspace/202506_ptl/WebContent/dp/damun/
dir.upload.default=C:/workspace/202506_ptl/WebContent/dp/bulletin/
dir.upload.default1=C:/workspace/202506_ptl/WebContent/dp1
dir.upload.developMeeting=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/meeting
dir.upload.edutarget=C:/workspace/202506_ptl/WebContent/dp/edutarget/
dir.upload.eportfolioknowledge=C:/workspace/202506_ptl/WebContent/eportfolio/uploads/career/
dir.upload.etest=C:/workspace/202506_ptl/WebContent/dp/etest/
dir.upload.etestimg=C:/workspace/202506_ptl/WebContent/dp/etest/
dir.upload.etestquestion=C:/workspace/202506_ptl/WebContent/dp/etest/
dir.upload.exam=C:/workspace/202506_ptl/WebContent/dp/exam/
dir.upload.exam.file=C:/workspace/202506_ptl/WebContent/dp/exam/file
dir.upload.examcourse.file=C:/workspace/202506_ptl/WebContent/dp/examcourse/file
dir.upload.fairImage=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/fairImage
dir.upload.fairThumb=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/fairThumb
dir.upload.goyong=C:/workspace/202506_ptl/WebContent/dp/goyong/
dir.upload.helpfile=C:/workspace/202506_ptl/WebContent/eportfolio/uploads/help/
dir.upload.ibox=C:/workspace/202506_ptl/WebContent/dp/bulletin/ibox
dir.upload.intellect=C:/workspace/202506_ptl/WebContent/dp/bulletin/boards/intellect
dir.upload.knowledgeucc=C:/workspace/202506_ptl/WebContent/dp/knowledgeucc/normal/
dir.upload.knowledgeuccNew=C:/workspace/202506_ptl/WebContent/dp/resource/vod/
dir.upload.learncom.Cop=C:/workspace/202506_ptl/WebContent/dp/bulletin/learncom/cop
dir.upload.learncom.Cop.ActFinalReport=C:/workspace/202506_ptl/WebContent/dp/bulletin/learncom/cop/actFinalReport
dir.upload.learncom.Cop.ActMiddleReport=C:/workspace/202506_ptl/WebContent/dp/bulletin/learncom/cop/actMiddleReport
dir.upload.learncom.Cop.Board=C:/workspace/202506_ptl/WebContent/dp/bulletin/learncom/cop/board
dir.upload.liktboard=C:/workspace/202506_ptl/WebContent/dp/mentor/
dir.upload.linksite=C:/workspace/202506_ptl/WebContent/dp/linksite/
dir.upload.mailfile=C:/workspace/202506_ptl/WebContent/dp/mailfile/
dir.upload.mentoinfo=C:/workspace/202506_ptl/WebContent/dp/mentor/
dir.upload.miniLectureThumb=C:/workspace/202506_ptl/WebContent/vod/miniLecture/thumb
dir.upload.miniLectureVideo=C:/workspace/202506_ptl/WebContent/vod/miniLecture/video
dir.upload.outuseradmin=C:/workspace/202506_ptl/WebContent/dp/comp/
dir.upload.postfile=C:/workspace/202506_ptl/WebContent/eportfolio/uploads/post/
dir.upload.project=C:/workspace/202506_ptl/WebContent/dp/project/
dir.upload.propose=C:/workspace/202506_ptl/WebContent/dp/accept/
dir.upload.proposewizard=C:/workspace/202506_ptl/WebContent/dp/edutarget/
dir.upload.qnabycourse=C:/workspace/202506_ptl/WebContent/dp/qnabycourse/
dir.upload.report=C:/workspace/202506_ptl/WebContent/dp/report/
dir.upload.research=C:/workspace/202506_ptl/WebContent/dp/research/
dir.upload.researchmng=C:/workspace/202506_ptl/WebContent/dp/researchmng/
dir.upload.resource=C:/workspace/202506_ptl/WebContent/dp/resource/
dir.upload.resrcdomng=C:/workspace/202506_ptl/WebContent/dp/researcdomng/
dir.upload.scobject=/emc_backup/LMS/content/temp/
dir.upload.script.file=C:/workspace/202506_ptl/WebContent/vod/miniLecture/script/dec
dir.upload.sepcialeduhistory=C:/workspace/202506_ptl/WebContent/dp/sepcialeduhistory
dir.upload.studyadminboard=C:/workspace/202506_ptl/WebContent/dp/studyadminboard/
dir.upload.studyadmindata=C:/workspace/202506_ptl/WebContent/dp/studyadmindata/
dir.upload.subject=C:/workspace/202506_ptl/WebContent/dp/subject/
dir.upload.subjinfo=C:/workspace/202506_ptl/WebContent/dp/subjinfo/
dir.upload.sulmun=C:/workspace/202506_ptl/WebContent/dp/research/
dir.upload.temp=C:/workspace/202506_ptl/WebContent/dp/bulletin/temp
dir.upload.textbook=C:/workspace/202506_ptl/WebContent/dp/book/
dir.upload.tutor=C:/workspace/202506_ptl/WebContent/dp/tutor/
download.apk.dir=C:/workspace/202506_ptl/WebContent/dp/bulletin/apk
epf.cssPath.value=/eportfolio/css
epf.flashPath.value=http://cresys-eportfolio.credu.com/eportfolio/flash
epf.imgPath.value=/eportfolio/images
epf.jsPath.value=/eportfolio/js
epf.skinCssPath.value=/eportfolio/css_skin
epf.upload.default=/eportfolio/uploads
epf.url.value=http://cresys-eportfolio.credu.com
error.massage.show=Y
error.message.view=true
excelupload.dir=C:/workspace/202506_ptl/WebContent/excelupload
file.size=centerdeskevent;scobject;studyadmindata;resourceadmin;resource;
file.size.centerdeskevent=1
file.size.default=500
file.size.resource=300
file.size.resourceadmin=500
file.size.scobject=500
file.size.studyadmindata=200
file.type=centerdeskevent;
file.type.centerdeskevent=jpg;gif;pdf;PDF;
file.type.default=jpg;gif;png;doc;docx,zip;ppt;pptx;xls;xlsx;hwp;txt;pdf;wmv;avi;pdf;mp3;mpg;wma;mp4;flv;alz;msg;
gemini.api.key=
gemini.model=gemini-2.5-flash
jasypt.decrypted.key=
jasypt.key=
ktedu.app.dir=C:/workspace/202506_ptl/WebContent/dp/app
ktedu.app.enckey=
ktedu.cdn.url=https://ktedufrontdoor-hrgpcfgwgkdsdghw.a02.azurefd.net
ktedu.codegenius.domain=https://dev.codegenius.edu-tech.io/
ktedu.codegenius.enckey=
ktedu.con.url=https://dev.ktedu.kt.com:1443
ktedu.exam.domain=http://localhost:8082
ktedu.exam.expiration-time=86400000
ktedu.exam.secret-key=
ktedu.fastcampus.domain=https://skillflo.io/external/sso
ktedu.fastcampus.enckey=
ktedu.fastcampus.expiration-time=86400000
ktedu.lms.secret-key=***MASKED***
ktedu.lms.was.domain=http://localhost:8083
ktedu.main.mobile.url=/mobile/m/main/portalMain.do
ktedu.main.tablet.url=/mobile/t/main/portalMain.do
ktedu.main.url=/main/portalMain.do
ktedu.solrserver=http://10.217.183.89:8983/solr/WMS
ktedu.stream.url=https://dev.ktedu.kt.com:1443
ktedu.url=http://localhost:8080
ktedu.video.dir=/vod/miniLecture/video/
ktedu.was.root.path=C:/workspace/202506_ptl/WebContent
ldap.base.dn=OU=Employee,DC=ldap,DC=ktlab,DC=dev
ldap.conn.id=lms_ldapdevuser
ldap.conn.pd=***MASKED***
ldap.host=tbldap01.ldap.ktlab.dev
ldap.port=636
learningAct.upload.dir=C:/workspace/202506_ptl/WebContent/learningAct
log.autoflush=true
log.dir.err=C:/workspace/202506_ptl/WebContent/log/err/
log.dir.info=C:/workspace/202506_ptl/WebContent/log/info/
log.dir.mail=C:/workspace/202506_ptl/WebContent/log/mail/
log.dir.sys=C:/workspace/202506_ptl/WebContent/log/sys/
log.err.trace=true
log.info.trace=true
log.mail.trace=true
log.sys.trace=true
login.except.isuse=true
login.except.value=5

# source: src/conf/mail.properties
mail.act=v_act
mail.actcnt=v_actcnt

# source: src/conf/cresys.properties
mail.admin.comptel=052-230-2312
mail.admin.email=ktedu@kt.com
mail.admin.name=\uc778\uc7ac\uac1c\ubc1c\uc6d0
mail.admin.singlesender=true

# source: src/conf/mail.properties
mail.anscontent=v_anscontent
mail.appcono=v_appcono
mail.appemail=v_appemail
mail.appjikwinm=v_appjikwinm
mail.appname=v_appname
mail.biyong=v_biyong
mail.compnm=v_compnm
mail.comptel=v_comptel
mail.cono=v_cono
mail.content=v_content
mail.daericompnm=v_daericompnm
mail.daericono=v_daericono
mail.daeriemail=v_daeriemail
mail.daerijikwinm=v_daerijikwinm
mail.daeriname=v_daeriname
mail.day1=v_day1
mail.day2=v_day2

# source: src/conf/cresys.properties
mail.dir.html=C:/workspace/202506_ptl/WebContent/learn/html/mail/

# source: src/conf/mail.properties
mail.edudays=v_edudays
mail.eduend=v_eduend
mail.edustart=v_edustart
mail.etc1=v_etc1
mail.etc2=v_etc2

# source: src/conf/cresys.properties
mail.file.name=C:/workspace/202506_ptl/WebContent/WEB-INF/classes/conf/mail.properties

# source: src/conf/mail.properties
mail.fromemail=v_fromemail
mail.fromname=v_fromname
mail.ftest=v_ftest
mail.gradscore=v_gradscore
mail.gradstep=v_gradstep
mail.grseqnm=v_grseqnm
mail.gubunstr=v_gubunstr
mail.insday=v_insday
mail.isapprovalstr=v_isapprovalstr
mail.isgraduated=v_isgraduated
mail.isonoff=v_isonoff
mail.month=v_thismon
mail.month1=v_month1
mail.month2=v_month2
mail.mtest=v_mtest
mail.name=v_name
mail.passday=v_passday
mail.place=v_place
mail.point=v_point
mail.propycnt=v_propycnt
mail.pswd=v_pwd
mail.quecontent=v_quecontent
mail.quetitle=v_quetitle
mail.rejectedreason=v_rejectedreason
mail.repcono=v_repcono
mail.repemail=v_repemail
mail.repjikwinm=v_repjikwinm
mail.repname=v_repname
mail.report=v_report
mail.reportcnt=v_reportcnt
mail.sdesc=v_sdesc
mail.seat=v_seat

# source: src/conf/cresys.properties
mail.server=http://147.6.87.14:8080/ems52/AutoSendIFPop.do

# source: src/conf/mail.properties
mail.stoldcnt=v_stoldcnt
mail.stoldncnt=v_stoldncnt
mail.stoldycnt=v_stoldycnt
mail.studentlimit=v_studentlimit
mail.subject=v_subject
mail.subjnm=v_subjnm
mail.teduseq=v_eduseq
mail.teduseqnm=v_eduseqnm
mail.testcnt=v_testcnt
mail.tispass=v_ispass
mail.toname=v_toname
mail.tstep=v_tstep
mail.tyear=v_year
mail.url=v_url
mail.userid=v_userid
mail.wact=v_wact
mail.wetc1=v_wetc1
mail.wetc2=v_wetc2
mail.wftest=v_wftest
mail.wgradstep=v_wgradstep
mail.wmtest=v_wmtest
mail.wreport=v_wreport
mail.year=v_year
mail.year1=v_year1
mail.year2=v_year2

# source: src/conf/scorm2004.properties
org.adl.util.debug.print.console.datamodel=false
org.adl.util.debug.print.console.misc=false
org.adl.util.debug.print.console.samplerte=false
org.adl.util.debug.print.console.sequencer=false
org.adl.util.debug.print.console.testsuite=true
org.adl.util.debug.print.console.validator=false
org.adl.util.debug.print.file.datamodel=false
org.adl.util.debug.print.file.misc=false
org.adl.util.debug.print.file.samplerte=false
org.adl.util.debug.print.file.sequencer=false
org.adl.util.debug.print.file.testsuite=false
org.adl.util.debug.print.file.validator=false
org.adl.util.debug.timestamp.console.datamodel=false
org.adl.util.debug.timestamp.console.misc=false
org.adl.util.debug.timestamp.console.samplerte=false
org.adl.util.debug.timestamp.console.sequencer=false
org.adl.util.debug.timestamp.console.testsuite=false
org.adl.util.debug.timestamp.console.validator=false
org.adl.util.debug.timestamp.file.datamodel=false
org.adl.util.debug.timestamp.file.misc=false
org.adl.util.debug.timestamp.file.samplerte=false
org.adl.util.debug.timestamp.file.sequencer=false
org.adl.util.debug.timestamp.file.testsuite=false
org.adl.util.debug.timestamp.file.validator=false

# source: src/conf/cresys.properties
page.bulletin.row=10
pool.name=zpack
pool.name.mssql=lmssql

# source: src/conf/spring/KT-properties.xml#inline
redirectContentType=text/html;charset=EUC-KR
rowsPerPage=10

# source: src/conf/cresys.properties
server.type=local
sms.admin.comptel=080-224-9696
sso.path=C:/workspace/202506_ptl/WebContent/portal.store
url.upload=/dp/
